### ISSUE TITLE
Necessary prerequisites to compiling llama

### ISSUE THREAD

**Issue by kevinkaw** [thisserand/llama2_local#4]
here's what i did to make the compilation successful. please add the following to the readme/instructions/guide:

1. CMake version [cmake-3.27.0-windows-x86_64.msi](https://cmake.org/download/) installed to root directory ("C:\") 
2. minGW64 version [11.0.0](https://www.mingw-w64.org/downloads/#winlibscom) extracted to root directory ("C:\")
3. set environment path variables for CMake and minGW64
4. install [visual studio build tools](https://visualstudio.microsoft.com/downloads/). It's way at the bottom under "Tools for Visual Studio" drop down list.
5. In visual studio, check the "Desktop development with c++", click install.

Then you can compile successfully.

**Comment by thisserand** [comment]
Thanks, I will add it to the README. :-)

**Comment by kevinkaw** [comment]
Hey thanks for the credit! :D The hyperlinks aren't there though?
